In [1]:
import pandas as pd
import numpy as np

In [2]:
cars_train = pd.read_csv(r"cars_train.csv",header=None)
cars_test = pd.read_csv(r"cars_test.csv",header=None)

In [3]:
print(cars_train.shape)
cars_train.head()

(1382, 7)


0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [4]:
print(cars_test.shape)
cars_test.head()

(346, 7)


0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good

In [5]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [6]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [7]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

In [8]:
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [9]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

No MIssing values Found

In [10]:
cars_test.drop("classes",axis=1,inplace=True)
cars_test.head()


## Dropping the Classes variable from the test data set to create a senario, so that we can predict a Y(classes variable)

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [11]:
colname = cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [21]:
# Converting categorical data to numerical using LabelEncoder for cars_train Dataset

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for x in colname:
    cars_train[x] = le.fit_transform(cars_train[x])

In [16]:
cars_train.head()
# acc ==> 0
# good ==> 1
# unacc ==> 2
# vgood ==> 3

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [17]:
colname_test = cars_test.columns
colname_test

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [19]:
# Converting categorical data to numerical using LabelEncoder for cars_test Dataset

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for x in colname_test:
    cars_test[x] = le.fit_transform(cars_test[x])

In [20]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [22]:
# Creating X and Y for cars_train dataset

X=cars_train.values[:,0:-1]  # All the columns except "classes" variable
Y=cars_train.values[:,-1]    # Only the "classes" variable
Y=Y.astype(int)


In [25]:
print(X.shape)
print(Y.shape)

(1382, 6)
(1382,)


In [26]:
# Scaling the data[Optional] Just for better practice.

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [28]:
print(X)

[[ 1.33507272 -1.3488262  -0.45682233  1.21505861  1.22565305  0.00176987]
 [-0.44760409  1.32688358 -0.45682233 -0.01064285  1.22565305  1.22474807]
 [-0.44760409 -1.3488262   1.33418038  1.21505861 -1.21505663  0.00176987]
 ...
 [-1.33894249  1.32688358  1.33418038 -0.01064285  0.00529821 -1.22120833]
 [ 0.44373431  0.43498032  0.43867903 -0.01064285 -1.21505663  0.00176987]
 [ 0.44373431 -0.45692294  1.33418038  1.21505861  1.22565305 -1.22120833]]


In [29]:
# Splitting the data into train and test(validation)

from sklearn.model_selection import train_test_split

#Split the data into test and train 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,random_state=10)

##### Building the model

In [39]:
# Creating the model

from sklearn.tree import DecisionTreeClassifier

model_DecisionTree = DecisionTreeClassifier(random_state=10,criterion="gini")

# Training the model with the help of fit function
model_DecisionTree.fit(X_train,Y_train)

# Predicting using the predict function
Y_pred = model_DecisionTree.predict(X_test)

print(list(zip(Y_train,Y_pred)))

[(0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 0), (2, 2), (2, 2), (2, 1), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (0, 2), (2, 2), (2, 2), (2, 2), (0, 2), (0, 2), (2, 2), (2, 2), (2, 0), (3, 2), (2, 0), (0, 0), (2, 2), (2, 2), (0, 2), (2, 0), (2, 2), (2, 2), (2, 0), (0, 2), (2, 2), (0, 2), (0, 2), (0, 2), (2, 3), (2, 0), (0, 2), (2, 0), (0, 3), (2, 0), (1, 2), (2, 0), (0, 2), (2, 2), (0, 2), (1, 2), (0, 2), (2, 2), (2, 0), (0, 2), (2, 0), (0, 2), (2, 2), (2, 0), (0, 2), (2, 2), (2, 0), (2, 2), (2, 0), (2, 0), (2, 2), (2, 2), (0, 0), (0, 3), (2, 0), (2, 0), (2, 2), (0, 2), (2, 0), (2, 2), (2, 0), (2, 2), (3, 2), (2, 0), (3, 2), (2, 2), (1, 0), (0, 2), (2, 2), (2, 2), (2, 0), (0, 2), (2, 2), (2, 0), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 0), (2, 3), (0, 2), (1, 2), (2, 0), (2, 0), (1, 2), (0, 2), (2, 2), (0, 0), (2, 2), (2, 0), (2, 3), (2, 2), (2, 0), (2, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 3), (2, 2), (2, 0), (2, 2), (2, 0),

##### Evaluating the model

In [34]:
## Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
print(confusion_matrix(Y_test,Y_pred))
 
print("\n Classification report: ")
print(classification_report(Y_test,Y_pred))

print(f"Accuracy of the model: {accuracy_score(Y_test, Y_pred)}")

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]

 Classification report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model: 0.9783393501805054


In [38]:
model_DecisionTree.score(X_train,Y_train)

# The Accuracy on the Training Data is 100 % but at the sametime the accuracy on the test data is also about 98%.
# This Indicates that the model might not be an over fitted model

1.0

In [44]:
## Zipping The independent variables name with the Model feature importance value list.
# feature_importance_ helps to find the contribution to the growth of tree.
# the total of all the feature_importances is equal to 1 which means 100% of contribution
# In this Output we may get to see some variables returning a 0.0000 kind of values or a very negligible value like 0.00005
# This variables can be eliminated given that they are showing 0 or very low contribution to the growth of the tree.
# A 0 value indicates that the variable was never found as a significant variable and was never use for spliting the tree.

print((list(zip(cars_train.columns[0:-1],
               model_DecisionTree.feature_importances_))))

[('buying', 0.21976792783843332), ('maint', 0.18220929667385857), ('doors', 0.062005934167191426), ('persons', 0.19425872158174767), ('lug_boot', 0.09772725134941933), ('safety', 0.24403086838934968)]


In [45]:
# Turning the Above list into  a Dataframe, To view the result to more interpretable manner

sample=pd.DataFrame()
 
sample["Column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
 
sample.sort_values("Imp value",ascending=False)

Column  Imp value
5    safety   0.244031
0    buying   0.219768
3   persons   0.194259
1     maint   0.182209
4  lug_boot   0.097727
2     doors   0.062006